version: '3'
services:
  postgres_db10:
    image: postgres:14-alpine
    container_name: "postgres10"
    environment:
      POSTGRES_PASSWORD: "123World000%"
      POSTGRES_DB: "francisco_lunadb"
      POSTGRES_USER: "francisco_luna"
    ports:
      - "10010:5510"
    volumes:
      - "/home/francisco_luna/postgres:/usr/src/postgres"
    networks:
      - our-library-net
    command: -p 5510

  web10:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8010"
    container_name: "django10"
    depends_on:
      - postgres_db10
    environment:
      PSQL_DBNAME: "francisco_lunadb"
      PSQL_USERNAME: "francisco_luna"
      PSQL_PASS: "123World000%"
      PSQL_HOST: "172.24.0.16"
      PSQL_PORT: "5510"
    volumes:
      - "/home/francisco_luna/Django-REST-Exercise:/usr/src/django/library"
    ports:
      - "9010:8010"
    networks:
      - our-library-net
networks:
  our-library-net:
    external: true
    driver: bridge

